import {BuildingsIcon, CheckIcon, CircleIcon, CopyrightIcon, DeviceMobileIcon, FlagBannerIcon, UserFocusIcon, WalletIcon} from '@phosphor-icons/react'
import {InputField} from '@/types/InputField'
import {getCountries} from '@/utils/getCountries'

const profileFields: InputField[] = [
    {
        labelText: 'firstname',
        labelFor: 'profileFirstname',
        id: 'profileFirstname',
        name: 'profileFirstname',
        type: 'text',
        autoComplete: 'firstname',
        isRequired: false,
        placeholder: 'firstname',
        icon: UserFocusIcon,
    },
    {
        labelText: 'lastname',
        labelFor: 'profileLastname',
        id: 'profileLastname',
        name: 'profileLastname',
        type: 'text',
        autoComplete: 'lastname',
        isRequired: false,
        placeholder: 'lastname',
        icon: UserFocusIcon,
    },
    {
        labelText: 'company',
        labelFor: 'profileCompany',
        id: 'profileCompany',
        name: 'profileCompany',
        type: 'text',
        autoComplete: 'company',
        isRequired: false,
        placeholder: 'company',
        icon: CopyrightIcon,
    },
    {
        labelText: 'country',
        labelFor: 'profileCountry',
        id: 'profileCountry',
        name: 'profileCountry',
        type: 'text',
        autoComplete: 'country',
        isRequired: false,
        placeholder: 'country',
        icon: FlagBannerIcon,
        isDropdown: true,
        dropdownData: getCountries(),
    },
    {
        labelText: 'address',
        labelFor: 'profileAddress',
        id: 'profileAddress',
        name: 'profileAddress',
        type: 'text',
        autoComplete: 'address',
        isRequired: false,
        placeholder: 'address',
        icon: BuildingsIcon,
    },
    {
        labelText: 'phone',
        labelFor: 'profilePhone',
        id: 'profilePhone',
        name: 'profilePhone',
        type: 'text',
        autoComplete: 'phone',
        isRequired: false,
        placeholder: 'phone',
        icon: DeviceMobileIcon,
    },
    {
        labelText: 'low_balance_notification',
        labelFor: 'profileLowBalanceNotification',
        id: 'profileLowBalanceNotification',
        name: 'profileLowBalanceNotification',
        type: 'checkbox',
        autoComplete: 'low_balance_notification',
        isRequired: false,
        placeholder: 'low_balance_notification',
        icon: CheckIcon,
    },
    {
        labelText: 'low_balance_edge',
        labelFor: 'profileLowBalanceEdge',
        id: 'profileLowBalanceEdge',
        name: 'profileLowBalanceEdge',
        type: 'number',
        autoComplete: 'low_balance_edge',
        isRequired: false,
        placeholder: 'low_balance_edge',
        icon: WalletIcon,
    },
    {
        labelText: 'subscribe_news',
        labelFor: 'profileSubscribeNews',
        id: 'profileSubscribeNews',
        name: 'profileSubscribeNews',
        type: 'checkbox',
        autoComplete: 'subscribe_news',
        isRequired: false,
        placeholder: 'subscribe_news',
        icon: CircleIcon,
    },

]
export {profileFields}
